version: '3'
services:
  go:
    container_name: golang-kafka
    build:
      context: "./"
      args:
        - VARIANT=1.17
        - NODE_VERSION=lts/*
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ../:/workspace/